#!/usr/bin/env python3
"""Builds the deployable site from src/ (run from the project root: python3 tools/build.py).

Outputs:
  public/index.html                    the website
  public/admin/index.html              the admin panel
  netlify/functions/_lib/defaults.mjs  default content for the backend
  preview/preview.html                 single-file demo (site + admin) for previews
"""
import json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
P = lambda *a: os.path.join(ROOT, *a)
read = lambda p: open(P(p), encoding="utf-8").read()
def write(p, s):
    os.makedirs(os.path.dirname(P(p)), exist_ok=True)
    open(P(p), "w", encoding="utf-8").write(s)

defaults = json.loads(read("content.default.json"))
defaults_js = json.dumps(defaults, ensure_ascii=False)
shared = read("src/shared.js").replace("/*DEFAULTS_JSON*/", defaults_js)
site = read("src/site.html").replace("/*SITE_CSS*/", read("src/site.css")).replace("/*SHARED_JS*/", shared)
admin = read("src/admin.html").replace("/*SHARED_JS*/", shared)

HEAD = '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n'
def document(body_html):
    # split leading <title>/<meta>/<link>/<style> into <head>
    m = re.search(r"</style>\s*", body_html)
    head, rest = body_html[: m.end()], body_html[m.end():]
    return HEAD + head + "\n</head>\n<body>\n" + rest + "\n</body>\n</html>\n"

write("public/index.html", document(site))
write("public/admin/index.html", document(admin))
write("netlify/functions/_lib/defaults.mjs",
      "// Generated by tools/build.py from content.default.json. Edit that file instead.\nexport default " +
      json.dumps(defaults, ensure_ascii=False, indent=2) + ";\n")

# ---------- preview: site + admin in one file (admin at #admin) ----------
def scope_css(css, prefix="#admin-root"):
    out, i = [], 0
    while True:
        j = css.find("{", i)
        if j < 0: break
        head = css[i:j].strip()
        depth, k = 1, j + 1
        while depth:
            depth += {"{": 1, "}": -1}.get(css[k], 0); k += 1
        body = css[j + 1:k - 1]
        head = re.sub(r"/\*.*?\*/", "", head, flags=re.S).strip()
        if head.startswith("@media"):
            out.append(head + "{" + scope_css(body, prefix) + "}")
        elif head.startswith("@"):
            out.append(head + "{" + body + "}")
        else:
            sels = [s.strip() for s in head.split(",")]
            out.append(",".join(s if prefix in s else f"{prefix} {s}" for s in sels) + "{" + body + "}")
        i = k
    return "\n".join(out)

a_css = re.search(r"<style>(.*?)</style>", admin, re.S).group(1)
a_body = admin[admin.index("</style>") + 8:]
a_body = a_body.replace(shared, "window.__ADMIN_EMBEDDED=true;")  # site already defines LBL
preview_extra_css = """
body.admin-mode>*:not(#admin-root):not(.a-toast):not(script){display:none!important}
#admin-root{display:none}
body.admin-mode #admin-root{display:block;position:fixed;inset:0;z-index:200;overflow:auto}
.try-admin{position:fixed;left:16px;bottom:calc(16px + env(safe-area-inset-bottom,0px));z-index:60;font:600 .95rem var(--disp);background:#fff;border:2px solid var(--ink);border-radius:999px;padding:9px 16px;box-shadow:3px 3px 0 var(--ink);color:var(--ink);text-decoration:none}
"""
preview_router = """
<script>
(()=>{function r(){const on=location.hash==="#admin";document.body.classList.toggle("admin-mode",on);if(!on&&window.__reloadDemo)window.__reloadDemo()}
addEventListener("hashchange",r);r();})();
</script>"""
preview = site.replace("</style>", scope_css(a_css) + preview_extra_css + "</style>", 1)
preview = preview.replace("<title>Lens By Lyssa</title>", "<title>Lens By Lyssa</title>", 1)
preview = preview.replace('<div class="toast" id="toast"', '<a class="try-admin" href="#admin">✎ Try the admin panel</a>\n<div class="toast" id="toast"', 1)
preview += "\n" + a_body + preview_router
write("preview/preview.html", preview)
print("built: public/index.html, public/admin/index.html, _lib/defaults.mjs, preview/preview.html")
